### ISSUE TITLE
引用Task问题

### ISSUE THREAD

**Issue by brucewuu520** [mcxiaoke/Android-Next#11]
![error](https://cloud.githubusercontent.com/assets/3361243/9158624/d3f5132e-3f4c-11e5-933e-7580442a8e2f.png)
task应该对Android的版本的版本没什么要求吧？为什么要设置10以上呢？

**Comment by mcxiaoke** [comment]
@brucewuu520 10就是Android 2.3.3 ，现在绝大部分都是2.3甚至4.0以上的版本了，你需要在 build.gradle 的 defaultConfig部分加上 minSdkVersion 10，这里根据你项目的实际情况，大于等于10即可

**Comment by brucewuu520** [comment]
当前还有5.7%的用户用的仍然是9，如果task对Android版本没什么特别的需求，是不是可以不用设置最低版本啊？

**Comment by mcxiaoke** [comment]
@brucewuu520 这是我基于个人项目和公司项目，还有友盟等的统计数据考虑的
