### ISSUE TITLE
The first visible item position can be easily got

### ISSUE THREAD

**Issue by KungFuBrother** [mcxiaoke/Android-Next#13]
int firstVisibleItem = recyclerViewHelper.findFirstVisibleItemPosition();

new:
recyclerView.getChildAdapterPosition(recyclerView.getChildAt(0));

**Comment by KungFuBrother** [comment]
why not use this?  RecyclerView.SCROLL_STATE_SETTLING

**Comment by mcxiaoke** [comment]
close
