### ISSUE TITLE
关于线程这块的疑问

### ISSUE THREAD

**Issue by brucewuu520** [mcxiaoke/Android-Next#14]
我看这个版本更改了实现单线程执行的方法，那么如果我这么调用：
TaskBuilder.create(resultType|callable|callback)
         .success(success)
         .failure(failure)
         .with(caller) 
         .on(TaskQueue.singleThread()).start();
每次调用都会产生一个新的TaskQueue对象，就不是单例了，线程也不能串行了吧？
如果我在调用前设置一个全局的TaskQueue = TaskQueue.singleThread()，就有悖这种链式调用的简洁性，该怎么破？

**Comment by mcxiaoke** [comment]
可以在Application里放一个全局的TaskQueue，然后 app.getQueue()
